[package]
name = "calmerge"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ical = { version = "0.10.0", features = ["ical", "vcard"] }
ics = "0.5.8"
rocket = "0.5.0"
